import type { Metadata } from "next";

import {RootLayout} from '@repo/ui/lib'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Root = ({children,}:React.PropsWithChildren) => <RootLayout>{children}</RootLayout>  

export default Root  
